### ISSUE TITLE
Dockerfileを用意してイメージビルド可能にする

### ISSUE THREAD

**Issue by Ruketa** [Ruketa/s2s-be#2]
docker run で実行したらサーバ起動するようにする。

anacondaのイメージは大きすぎるのでpythonの公式イメージにパッケージ追加して作りたい

**Comment by Ruketa** [comment]
docker環境構築 #5 で解決されたのでクローズします。

**Comment by hirojixx** [comment]
docker-compose up で
db及びバックエンドが起動します
